spring:
  application:
    name: windband-manager

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:windband}
    username: ${DB_USER:windband}
    password: ${DB_PASS:windband}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  thymeleaf:
    cache: false

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER:}
    password: ${MAIL_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:windband-manager}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:windband-secret-key-change-in-production-2026}
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: keycloak
        provider:
          keycloak:
            authorization-uri: http://keycloak.michalbzowski.pl/realms/${KEYCLOAK_REALM:windband}/protocol/openid-connect/auth
            token-uri: http://localhost:8180/realms/${KEYCLOAK_REALM:windband}/protocol/openid-connect/token
            jwk-set-uri: http://localhost:8180/realms/${KEYCLOAK_REALM:windband}/protocol/openid-connect/certs
            user-info-uri: http://localhost:8180/realms/${KEYCLOAK_REALM:windband}/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username



server:
  port: ${SERVER_PORT:8080}

app:
  base-url: ${BASE_URL:http://localhost:8080}
  keycloak:
    url: ${KEYCLOAK_PUBLIC_URL:http://localhost:8180}
    realm: ${KEYCLOAK_REALM:windband}
    client-id: ${KEYCLOAK_CLIENT_ID:windband-manager}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:windband-secret-key-change-in-production-2026}
    registration-redirect-url: ${app.keycloak.url}/realms/${app.keycloak.realm}/protocol/openid-connect/registrations?client_id=${app.keycloak.client-id}&redirect_uri=${app.base-url}/register&response_type=code&scope=openid profile email}