-- Migration V36: COMPOSITION_INSTRUMENTS link entity (US-1.3) - DISABLED no-op.
-- Kept as a comment-only file so that re-validation against shared databases that
-- already recorded version 36 as FAILED (and hold the OLD checksum from the broken
-- original) does not raise an integrity error, and so the CREATE TABLE is not run
-- for a second time on databases where it already succeeded.
-- DO NOT delete this file and DO NOT add executable SQL to it: the corrected DDL for
-- this table now lives in V38_create_composition_instruments (see that file for the
-- exact reason). Editing the body of this file changes its checksum, which would trip
-- Flyway validate on databases that already ran the earlier revision.
