-- V9: Previously removed order_name/desc not null from inventory_orders.
-- No longer needed - item_name and description columns were removed from InventoryOrder entity.
-- This migration is intentionally empty (placeholder for Flyway versioning).
