package pl.michalbzowski.windband.domain.composition;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import pl.michalbzowski.windband.BaseIntegrationTest;
import pl.michalbzowski.windband.domain.band.BandRepository;

/**
 * Integration tests for the {@link InstrumentRoleMap} entity + repository (US-1.4).
 *
 * <p>Pins down:
 * <ul>
 *   <li>Full field round-trip ({@code sourceTag}, {@code targetRolePattern}, optional
 *       {@code description}, and the auto-managed {@code createdAt} / {@code updatedAt});</li>
 *   <li>Case-insensitive tag matching — "Trąbka" / "TRĄBKA" / "trąbka" all resolve to the same
 *       row, mirroring V39's unique index (H2 is generated by Hibernate, so this proves the query
 *       contract, not the SQL index itself);</li>
 *   <li>Band isolation — a mapping owned by band A is never returned to a band-B read, even when
 *       the tag and role strings are identical;</li>
 *   <li>Distinguishable-role fan-out — one tag may legally map to several distinct roles;</li>
 *   <li>Factory input validation — required band with a resolvable id, non-blank tag/role, and
 *       description handling (null or non-blank) BEFORE any instance escapes. All factory rejections
 *       surface as {@link IllegalArgumentException} so callers have one exception type to catch.</li>
 * </ul>
 */
class InstrumentRoleMapTest extends BaseIntegrationTest {

    @Autowired
    private BandRepository bandRepository;

    @Autowired
    private InstrumentRoleMapRepository repository;

    @Autowired
    private org.springframework.jdbc.core.JdbcTemplate jdbcTemplate;

    /** Track rows created by this test instance so cleanup deletes ONLY ours (shared Testcontainers DB). */
    private final List<Long> myIds = new ArrayList<>();

    @AfterEach
    void cleanup() {
        for (Long id : myIds) {
            jdbcTemplate.update("DELETE FROM instrument_role_map WHERE id = ?", id);
        }
        myIds.clear();
    }

    private InstrumentRoleMap saveMapping(Long bandId, String sourceTag, String role, String description) {
        pl.michalbzowski.windband.domain.band.Band band = bandRepository.findById(bandId).orElseThrow();
        InstrumentRoleMap row = repository.save(
                InstrumentRoleMap.forBand(band, sourceTag, role, description));
        myIds.add(row.getId());
        return row;
    }

    @Test
    @DisplayName("instrument_role_map_rows_are_persisted — all fields round-trip")
    void rows_are_persisted_with_full_field_set() {
        saveMapping(1L, "Trąbka", "Trąbka 1", "Trumpet B-flat — first seat");

        List<InstrumentRoleMap> band1 = repository.findAllByBandId(1L);
        InstrumentRoleMap reloaded = band1.stream()
                .filter(m -> m.getSourceTag().equalsIgnoreCase("Trąbka")
                        && m.getTargetRolePattern().equals("Trąbka 1"))
                .findFirst().orElseThrow();

        assertThat(reloaded.getId()).isNotNull();
        assertThat(reloaded.getBand().getId()).isEqualTo(1L);
        assertThat(reloaded.getSourceTag()).isEqualTo("Trąbka");
        assertThat(reloaded.getTargetRolePattern()).isEqualTo("Trąbka 1");
        assertThat(reloaded.getDescription()).isEqualTo("Trumpet B-flat — first seat");
        assertThat(reloaded.getCreatedAt()).isNotNull();
        assertThat(reloaded.getUpdatedAt()).isNotNull();

        // description is optional: a null round-trips as null, not as an empty string.
        saveMapping(1L, "Flet", "Flet 1", null);
        InstrumentRoleMap noDesc = repository.findAllByBandId(1L).stream()
                .filter(m -> m.getSourceTag().equalsIgnoreCase("Flet")
                        && m.getTargetRolePattern().equals("Flet 1"))
                .findFirst().orElseThrow();
        assertThat(noDesc.getDescription()).isNull();
    }

    @Test
    @DisplayName("case-insensitive tag lookup — every casing variant of 'Waltornia' hits the same row")
    void case_insensitive_tag_lookup_is_consistent() {
        saveMapping(1L, "Waltornia", "Waltornia 1", null);

        // Mixed-case lookups all resolve to the same single row.
        for (String variant : new String[] { "Waltornia", "waltoRNIA", "WALTORNIA" }) {
            List<InstrumentRoleMap> byId = repository.findByBandIdAndSourceTag(1L, variant);
            assertThat(byId).hasSize(1)
                    .extracting(InstrumentRoleMap::getSourceTag)
                    .containsExactly("Waltornia"); // stored value preserved, not the look-up casing
        }

        // A genuinely different tag returns nothing.
        assertThat(repository.findByBandIdAndSourceTag(1L, "Puzon")).isEmpty();
    }

    @Test
    @DisplayName("band isolation — a mapping owned by band A is invisible to band B reads")
    void cross_band_reads_never_leak() {
        saveMapping(1L, "Saksofon", "Saksofon 1", null); // band 1 owns this
        // band 2 starts empty for this (tag, role) pair.

        List<InstrumentRoleMap> band1 = repository.findAllByBandId(1L);
        assertThat(band1).anySatisfy(m -> {
            assertThat(m.getSourceTag()).isEqualTo("Saksofon");
            assertThat(m.getBand().getId()).isEqualTo(1L);
        });

        // Same tag + role on band 2 is a separate, empty namespace: the exact (band, tag, role)
        // triple lookup must come back empty.
        assertThat(repository.findByBandIdAndSourceTagAndTargetRolePattern(2L, "Saksofon", "Saksofon 1"))
                .isNotPresent();

        // An exact (band, tag, role) triple only hits in the owning band.
        assertThat(repository.findByBandIdAndSourceTagAndTargetRolePattern(1L, "saksofon", "Saksofon 1"))
                .isPresent()
                .get()
                .satisfies(m -> assertThat(m.getBand().getId()).isEqualTo(1L));
    }

    @Test
    @DisplayName("one tag may map to several distinct roles on the same band")
    void one_tag_fans_out_to_multiple_roles() {
        saveMapping(1L, "Puzon", "Puzon 1", null);
        saveMapping(1L, "puzon", "Puzon 2", "second trombone seat"); // lower-case tag — same logical tag

        List<InstrumentRoleMap> results = repository.findByBandIdAndSourceTag(1L, "PUZON");
        assertThat(results).hasSize(2)
                .extracting(InstrumentRoleMap::getTargetRolePattern)
                .containsExactlyInAnyOrder("Puzon 1", "Puzon 2");
    }

    @Test
    @DisplayName("factory validates input — null band / blank tag / blank role / blank description all rejected with IllegalArgumentException")
    void factory_input_validation() {
        pl.michalbzowski.windband.domain.band.Band band = bandRepository.findById(1L).orElseThrow();

        // Null band.
        assertThatThrownBy(() -> InstrumentRoleMap.forBand(null, "Trąbka", "Trąbka 1", null))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("band");

        // Blank / null tag and role — uniform IllegalArgumentException for both null and blank.
        assertThatThrownBy(() -> InstrumentRoleMap.forBand(band, null, "Trąbka 1", null))
                .isInstanceOf(IllegalArgumentException.class).hasMessageContaining("sourceTag must not be");
        assertThatThrownBy(() -> InstrumentRoleMap.forBand(band, "   ", "Trąbka 1", null))
                .isInstanceOf(IllegalArgumentException.class).hasMessageContaining("sourceTag must not be blank");
        assertThatThrownBy(() -> InstrumentRoleMap.forBand(band, "Trąbka", "", null))
                .isInstanceOf(IllegalArgumentException.class).hasMessageContaining("targetRolePattern must not be blank");

        // Description: null is legal, blank string is not.
        assertThatCode(() -> {
            InstrumentRoleMap ok = InstrumentRoleMap.forBand(band, "Trąbka", "Trąbka 1", null);
            assertThat(ok.getDescription()).isNull();
        }).doesNotThrowAnyException();

        assertThatThrownBy(() -> InstrumentRoleMap.forBand(band, "Trąbka", "Trąbka 1", "   "))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("description");

        // A band without a resolvable id cannot own a mapping (cross-band / detached guard).
        pl.michalbzowski.windband.domain.band.Band idless = pl.michalbzowski.windband.domain.band.Band.create(
                "Idless Band", "idless-band");
        assertThatThrownBy(() -> InstrumentRoleMap.forBand(idless, "Flet", "Flet 1", null))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("band.id required");

        // Tag/role are trimmed on the way in.
        InstrumentRoleMap trimmed = InstrumentRoleMap.forBand(band, "  Trąbka  ", "  Trąbka 1  ", null);
        assertThat(trimmed.getSourceTag()).isEqualTo("Trąbka");
        assertThat(trimmed.getTargetRolePattern()).isEqualTo("Trąbka 1");
    }

    @Test
    @DisplayName("delete(InstrumentRoleMap) removes only the targeted row — other band untouched")
    void delete_is_row_scoped() {
        InstrumentRoleMap myMapping1 = saveMapping(1L, "Tuba Test A", "Tuba Test A 1", null);
        InstrumentRoleMap myMapping2 = saveMapping(2L, "Tuba Test B", "Tuba Test B 1", null);

        // Deleting a band-1 row should not affect band-2 data at all.
        repository.delete(myMapping1);
        assertThat(repository.findAllByBandId(1L))
                .noneMatch(m -> m.getId().equals(myMapping1.getId()));
        assertThat(repository.findAllByBandId(2L))
                .anySatisfy(m -> {
                    assertThat(m.getId()).isEqualTo(myMapping2.getId());
                    assertThat(m.getSourceTag()).isEqualTo("Tuba Test B");
                });

        // Single-row delete is the intended per-row removal path (JPA-managed entity),
        // and it cleanly bypasses TransactionRequiredException that the derived-DELETE has
        // under this H2/JPA profile. The port's bulk-delete surface stays available for
        // admin "reset defaults" flows via repository.deleteAllByBandId(id).
    }
}
